### ISSUE TITLE
PassGAN did not compare with FLA?

### ISSUE THREAD

**Issue by seokinj** [brannondorsey/PassGAN#10]
You said that PassGAN did not compare their results to FLA ... (Results part in READ.md...)

However, I think PassGAN did compare their results to the results of FLA in the latest version paper..

Am I right?

**Comment by brannondorsey** [comment]
You are correct! This was not true when I originally released this implementation, but I'm pleased to see that the authors have updated the paper to include several comparisons. Thanks for bringing this to my attention.
