### ISSUE TITLE
Why use Tensorflow==1.4.1?

### ISSUE THREAD

**Issue by bpartin2009** [brannondorsey/PassGAN#11]
Is there a reason requirments.txt says tensorflow==1.4.1 and not the latest like 1.7.0 compatible with CUDA  9.1? Is it just what you had/have at the time or is there other library or dependency issues that pose an issue?

**Comment by brannondorsey** [comment]
I'm using tensorflow==1.4.1 because that is what the original authors of https://github.com/igul222/improved_wgan_training used, and I'm leveraging most of their code. I haven't tried with any other versions. It might work great, or it might need some love. PRs welcome ;)

**Comment by brannondorsey** [comment]
I've confirmed 1.4.1 to work, hence why it is in the requirements.txt.
