### ISSUE TITLE
Consider to Stop Hotlinking Hashes.org Files

### ISSUE THREAD

**Issue by m33x** [brannondorsey/PassGAN#2]
_Full disclosure, I'm **not** affiliated with Hashes.org._

Every visitor of Hashes.org can read the following disclaimer on their website

> We host Hashes.org out of our own pockets. Even a small donation can really help!

In your README.md file you are hotlinking a rather large (2.9 GB) file from their server.
Please consider to change this hyperlink to the homepage of Hashes.org, instead of pointing directly to the file. Independent of this, you really should promote donating for their services or stop linking their site completely. Otherwise you can be sure that the **great places to find those** will soon be gone.

Cheers!

**Comment by brannondorsey** [comment]
Thank you for this :) I've mirrored the LinkedIn file from Hashes.org and am serving it from GitHub now via the releases page. I've also included a note highlighting that Hashes.org appreciates donations. I definitely didn't mean to leech from Hashes.org as I greatly appreciate what they are doing. Thank you for bringing this to my attention and providing a suggestion to change the hotlink.

Happy holidays :smile_cat:
