### ISSUE TITLE
TensorFlow uses only single GPU

### ISSUE THREAD

**Issue by mikeryan** [brannondorsey/PassGAN#5]
I have a system with multiple GPUs, but the TensorFlow library only makes use of one of them. Is it possible to parallelize the training and password generation across multiple GPUs?

**Comment by brannondorsey** [comment]
In theory, probably, however I'm not tensorflow pro and this repo is primarily a refactoring of [improved_wgan_training](https://github.com/igul222/improved_wgan_training). I'd dig around the issues on that repo, or post a new one. If someone is able to help you out over there, or you make headwind with any code, I'm happy to integrate those changes in this repo.

**Comment by mikeryan** [comment]
Did you fix this issue? I didn't see any code updates in the commit history.

**Comment by brannondorsey** [comment]
I was doing a bit of old-issue pruning on this repo and closed this as I felt I answered the Q, and this isn't something that is currently slated for development. I'm happy to re-open this with instructions that PRs are welcome in the future if you'd like.
