### ISSUE TITLE
i have three training datas. How to use train.py to process these data?

### ISSUE THREAD

**Issue by Explorer1092** [brannondorsey/PassGAN#9]

**Comment by brannondorsey** [comment]
How do you mean? Would you like to train one model with the combined datasets or train three different models?

If you would like to do the first, simply combine all three datasets into one file. If you would like to do the second, then simply train three different models:

```bash
python train.py --output-dir model-1 --training-data data/model-1-training-data.txt
python train.py --output-dir model-2 --training-data data/model-2-training-data.txt
python train.py --output-dir model-3 --training-data data/model-3-training-data.txt
```
